export const apiTags = {
  user: 'User',
  workInfo: 'WorkInfo',
  eduInfo: 'EduInfo',
  offer: 'Offer',
  interview: 'Interview',
  conversation: 'Conversation',
  job: 'Job',
  postedJob: 'PostedJob',
  favorites: 'Favorites',
  invite: 'Invite',
  proposal: 'Proposal',
  freelancerrating: 'FreelancerRating',
  notification: 'Notification',
};
